/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author GBP17
 */
public class Page1 extends javax.swing.JPanel {

    /**
     * Creates new form Page1
     */
    public Page1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPage1 = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        labelApellido = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        labelDNI = new javax.swing.JLabel();
        campoDNI = new javax.swing.JTextField();
        labelDireccion = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();

        labelNombre.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 20)); // NOI18N
        labelNombre.setText("Nombres:");

        campoNombre.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 18)); // NOI18N

        labelApellido.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 20)); // NOI18N
        labelApellido.setText("Apellidos:");

        campoApellido.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 18)); // NOI18N

        labelDNI.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 20)); // NOI18N
        labelDNI.setText("DNI:");

        campoDNI.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 18)); // NOI18N

        labelDireccion.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 20)); // NOI18N
        labelDireccion.setText("Dirección:");

        campoDireccion.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 18)); // NOI18N

        botonRegistrar.setFont(new java.awt.Font("RobotoMono Nerd Font Mono", 0, 24)); // NOI18N
        botonRegistrar.setText("Registrar Datos");

        javax.swing.GroupLayout contentPage1Layout = new javax.swing.GroupLayout(contentPage1);
        contentPage1.setLayout(contentPage1Layout);
        contentPage1Layout.setHorizontalGroup(
            contentPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPage1Layout.createSequentialGroup()
                .addGroup(contentPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPage1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(contentPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPage1Layout.createSequentialGroup()
                                .addComponent(labelNombre)
                                .addGap(42, 42, 42)
                                .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                            .addGroup(contentPage1Layout.createSequentialGroup()
                                .addGroup(contentPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelApellido)
                                    .addComponent(labelDNI)
                                    .addComponent(labelDireccion))
                                .addGap(18, 18, 18)
                                .addGroup(contentPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoDireccion)
                                    .addComponent(campoDNI)
                                    .addComponent(campoApellido)))))
                    .addGroup(contentPage1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(botonRegistrar)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        contentPage1Layout.setVerticalGroup(
            contentPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPage1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(contentPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellido)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(contentPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDNI))
                .addGap(22, 22, 22)
                .addGroup(contentPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDireccion)
                    .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(botonRegistrar)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JPanel contentPage1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables
}
