/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author GBP17
 */
public class Page1Postulante extends javax.swing.JPanel {

    /**
     * Creates new form Page1Postulante
     */
    public Page1Postulante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNombreEvaluador = new javax.swing.JLabel();
        fieldNombreEvaluador2 = new javax.swing.JTextField();
        labelDireccionEvaluador = new javax.swing.JLabel();
        fieldDireccionEvaluador = new javax.swing.JTextField();
        labelDNIEvaluador = new javax.swing.JLabel();
        fieldDNIEvaluador = new javax.swing.JTextField();
        labelIEEvaluador = new javax.swing.JLabel();
        fieldIEEvaluador = new javax.swing.JTextField();
        labelCarreraEvaluador = new javax.swing.JLabel();
        fieldIEEvaluador1 = new javax.swing.JTextField();
        labelPromedioEvaluador = new javax.swing.JLabel();
        fieldIEEvaluador2 = new javax.swing.JTextField();
        labelIngresosEvaluador = new javax.swing.JLabel();
        fieldIngresosEvaluador = new javax.swing.JTextField();
        labelPersonasEvaluador = new javax.swing.JLabel();
        fieldPersonasEvaluador = new javax.swing.JTextField();
        labelBecaEvaluador = new javax.swing.JLabel();
        fieldBecaEvaluador = new javax.swing.JTextField();
        labelTelefonoEvaluador = new javax.swing.JLabel();
        fieldTelefonoEvaluador = new javax.swing.JTextField();
        botonPostulanteEnviar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        labelNombreEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N
        labelNombreEvaluador.setText("Nombres y Apellidos:");

        fieldNombreEvaluador2.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N

        labelDireccionEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N
        labelDireccionEvaluador.setText("Dirección");

        fieldDireccionEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N

        labelDNIEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N
        labelDNIEvaluador.setText("DNI:");

        fieldDNIEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N

        labelIEEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N
        labelIEEvaluador.setText("Intitución Educativa:");

        fieldIEEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N

        labelCarreraEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N
        labelCarreraEvaluador.setText("Carrera:");

        fieldIEEvaluador1.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N

        labelPromedioEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N
        labelPromedioEvaluador.setText("Promedio:");

        fieldIEEvaluador2.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N

        labelIngresosEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N
        labelIngresosEvaluador.setText("Ingresos Familiares:");

        fieldIngresosEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N

        labelPersonasEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N
        labelPersonasEvaluador.setText("Personas en el Hogar:");

        fieldPersonasEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N

        labelBecaEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N
        labelBecaEvaluador.setText("Beca:");

        fieldBecaEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N

        labelTelefonoEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N
        labelTelefonoEvaluador.setText("Telefono:");

        fieldTelefonoEvaluador.setFont(new java.awt.Font("Iosevka NFM Medium", 0, 18)); // NOI18N

        botonPostulanteEnviar.setFont(new java.awt.Font("Iosevka NFP Medium", 0, 18)); // NOI18N
        botonPostulanteEnviar.setText("Enviar Datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(labelBecaEvaluador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldBecaEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTelefonoEvaluador)
                .addGap(18, 18, 18)
                .addComponent(fieldTelefonoEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonPostulanteEnviar)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(labelIngresosEvaluador)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fieldIngresosEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelPersonasEvaluador)
                            .addGap(18, 18, 18)
                            .addComponent(fieldPersonasEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelNombreEvaluador)
                                    .addGap(27, 27, 27)
                                    .addComponent(fieldNombreEvaluador2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelIEEvaluador)
                                    .addGap(18, 18, 18)
                                    .addComponent(fieldIEEvaluador))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelDireccionEvaluador)
                                    .addGap(18, 18, 18)
                                    .addComponent(fieldDireccionEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelDNIEvaluador)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(fieldDNIEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelCarreraEvaluador)
                                    .addGap(18, 18, 18)
                                    .addComponent(fieldIEEvaluador1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(labelPromedioEvaluador)
                                    .addGap(12, 12, 12)
                                    .addComponent(fieldIEEvaluador2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(76, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefonoEvaluador)
                    .addComponent(fieldTelefonoEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPostulanteEnviar)
                    .addComponent(fieldBecaEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBecaEvaluador))
                .addGap(17, 17, 17))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNombreEvaluador)
                        .addComponent(fieldNombreEvaluador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDireccionEvaluador)
                        .addComponent(fieldDireccionEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelDNIEvaluador)
                        .addComponent(fieldDNIEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelIEEvaluador)
                        .addComponent(fieldIEEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCarreraEvaluador)
                            .addComponent(fieldIEEvaluador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPromedioEvaluador)
                            .addComponent(fieldIEEvaluador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelIngresosEvaluador)
                        .addComponent(fieldIngresosEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelPersonasEvaluador)
                        .addComponent(fieldPersonasEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(75, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPostulanteEnviar;
    private javax.swing.JTextField fieldBecaEvaluador;
    private javax.swing.JTextField fieldDNIEvaluador;
    private javax.swing.JTextField fieldDireccionEvaluador;
    private javax.swing.JTextField fieldIEEvaluador;
    private javax.swing.JTextField fieldIEEvaluador1;
    private javax.swing.JTextField fieldIEEvaluador2;
    private javax.swing.JTextField fieldIngresosEvaluador;
    private javax.swing.JTextField fieldNombreEvaluador2;
    private javax.swing.JTextField fieldPersonasEvaluador;
    private javax.swing.JTextField fieldTelefonoEvaluador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelBecaEvaluador;
    private javax.swing.JLabel labelCarreraEvaluador;
    private javax.swing.JLabel labelDNIEvaluador;
    private javax.swing.JLabel labelDireccionEvaluador;
    private javax.swing.JLabel labelIEEvaluador;
    private javax.swing.JLabel labelIngresosEvaluador;
    private javax.swing.JLabel labelNombreEvaluador;
    private javax.swing.JLabel labelPersonasEvaluador;
    private javax.swing.JLabel labelPromedioEvaluador;
    private javax.swing.JLabel labelTelefonoEvaluador;
    // End of variables declaration//GEN-END:variables
}
