package ClasesParaZava;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

public class addBeca extends javax.swing.JFrame {

    public addBeca() {
        initComponents();
        
        //Creación del grupo de botones
        //para que 2 botones no sean
        //seleccionados a la vez
        ButtonGroup bg = new ButtonGroup();
        bg.add(isDepor);
        bg.add(isAcadem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        isDepor = new javax.swing.JRadioButton();
        isAcadem = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addDescrip = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        addMonto = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        addDuracion = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        addDepor = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        addAcadem = new javax.swing.JTextPane();
        FinA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Becas");

        jLabel1.setText("Bienvenido a Añadir Becas");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Monto");

        jLabel4.setText("Duración");

        isDepor.setSelected(true);
        isDepor.setText("Deportiva");
        isDepor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isDeporMouseClicked(evt);
            }
        });
        isDepor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isDeporActionPerformed(evt);
            }
        });

        isAcadem.setText("Académica");
        isAcadem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isAcademMouseClicked(evt);
            }
        });

        jLabel5.setText("Tipo de Beca");

        jScrollPane1.setViewportView(addDescrip);

        jScrollPane2.setViewportView(addMonto);

        jScrollPane3.setViewportView(addDuracion);

        jScrollPane4.setViewportView(addDepor);

        jScrollPane5.setViewportView(addAcadem);

        FinA.setText("Añadir");
        FinA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane1)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(isAcadem)
                            .addComponent(isDepor)
                            .addComponent(FinA))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isDepor)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isAcadem)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(FinA)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isDeporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isDeporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isDeporActionPerformed

    private void FinAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinAActionPerformed
            //Añade las becas dependiendo de cual boton esta seleccionado
            if(isAcadem.isSelected()==true){
                Beca nuevaBeca = new BecaDeportiva(addDepor.getText(),addDescrip.getText(), Integer.parseInt(addMonto.getText()), Integer.parseInt(addDuracion.getText()));
                SistemaDeBecas.listaBecas.add(nuevaBeca);
                JOptionPane.showMessageDialog(this, "Beca Depotiva añadida con exito", "OK", JOptionPane.INFORMATION_MESSAGE);
            }else {
                Beca nuevaBeca = new BecaAcademica(addDescrip.getText(), Integer.parseInt(addMonto.getText()), Integer.parseInt(addDuracion.getText()), addAcadem.getText());
                SistemaDeBecas.listaBecas.add(nuevaBeca);
                JOptionPane.showMessageDialog(this, "Beca Académica añadida con exito", "OK", JOptionPane.INFORMATION_MESSAGE);
            }
            File.guardar(SistemaDeBecas.listaBecas, "BECAS.txt");
                
    }//GEN-LAST:event_FinAActionPerformed

    private void isDeporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isDeporMouseClicked
       //Previene escribir en la casilla no seleccionada
        addDepor.setEditable(true);
        addAcadem.setEditable(false);
    }//GEN-LAST:event_isDeporMouseClicked

    private void isAcademMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isAcademMouseClicked
       //Previene escribir en la casilla no seleccionada
        addDepor.setEditable(false);
        addAcadem.setEditable(true);
    }//GEN-LAST:event_isAcademMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addBeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addBeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addBeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addBeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addBeca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FinA;
    private javax.swing.JTextPane addAcadem;
    private javax.swing.JTextPane addDepor;
    private javax.swing.JTextPane addDescrip;
    private javax.swing.JTextPane addDuracion;
    private javax.swing.JTextPane addMonto;
    private javax.swing.JRadioButton isAcadem;
    private javax.swing.JRadioButton isDepor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
